 sudo: true
 
 language: java
 
 before_install:
  - chmod +x gradlew
 
 after_failure:
  - cat home/travis/build/evivar/Gradle/build/reports/tests/test/index.html
 
 jdk:
   - oraclejdk8
   - oraclejdk9
   - openjdk8
  
  
