 sudo: true
 
 language: java
 
 before_install:
  - chmod +x gradlew
 
 jdk:
   - oraclejdk8
   - oraclejdk9
   - openjdk8
   
 script:
  - ./gradlew clean publish -i --continue
  - ./gradlew -b finalize.gradle finalize -i

after_script:
  - git add .
  # something@example.com
  - git config user.email "${GIT_EMAIL}"
  # First Last
  - git config user.name "${GIT_NAME}"
  - git commit -m "updating outputs"
  # https://${GH_TOKEN}@github.com/asciidoctor/asciidoctor-gradle-examples.git
  - git push -f "${GIT_URL}" gh-pages > /dev/null 2>&1
  
  
