 sudo: true
 
 language: java
 
 before_install:
  - chmod +x gradlew
 
 jdk:
   - oraclejdk8
   - oraclejdk9
   - openjdk8
 
 script: gradle check --debug

 notifications:
  email:
    recipients:
      - evivar@ucm.es
    on_success: always # default: change
    on_failure: always # default: always
  
