/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public int suma(int a, int b) {
    	
    	return a+b;
    	
    }
}
